name: 'DockerHub Login'

description: 'Logs in to DockerHub'

runs:
  using: 'docker'
  image: 'docker:latest'

inputs:
  username:
    description: 'DockerHub username'
    required: true
  password:
    description: 'DockerHub password'
    required: true

outputs:
  time: 
    description: 'The time we greeted you'
    value: ${{ steps.time.outputs.time }}
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

container:
  image: docker:latest

  inputs:
    username: ${{ inputs.username }}
    password: ${{ inputs.password }}

  command: |
    echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin
