name: 'Common Steps'
description: 'Run common steps in the workflow'

runs:
  using: 'composite'
  #shell: bash
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask numpy matplotlib pytest
      shell: bash

    - name: Run tests and generate reports
      run: |
        mkdir -p tests/
        pytest test_app.py --doctest-modules --junitxml=tests/test-results-${{ matrix.python-version }}.xml > tests/log1.txt 
        # You might need additional commands to generate test reports (e.g., coverage)
      shell: bash

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: tests/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
