name: 'Docker Login Action'
description: 'Logs in to Docker Hub'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      shell: bash
  
