name: 'Docker Login Action'
description: 'Logs in to Docker Hub'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true

runs:
  using: 'docker'
  image: 'alpine:latest'
  entrypoint: /bin/sh
  script: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
