name: 'DockerHub Login'

description: 'Logs in to DockerHub'

runs:
  using: 'docker'
  image: 'docker:latest'

inputs:
  username:
    description: 'DockerHub username'
    required: true
  password:
    description: 'DockerHub password'
    required: true

env:
  DOCKERHUB_USERNAME: ${{ inputs.username }}
  DOCKERHUB_PASSWORD: ${{ inputs.password }}

container:
  image: docker:latest

  command: |
    echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
